blog/urls.py
from django.urls import include, path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),
    path('<int:pk>/', views.BlogDetail.as_view(), name='blog_detail'),
    path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments'),
]

orders/urls.py
from django.urls import include, path

from orders.views import OrderCreateView, OrderDetailView, OrderListView

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order'),
    path('', OrderListView.as_view(), name='orders_list'),
]

store/urls.py
"""сохранить конфигурацию URL-адреса

Список `urlpatterns` направляет URL-адреса в представления. Для получения дополнительной информации см.:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Примеры:
Представления функций
    1. Добавьте импорт: из представлений импорта my_app
    2. Добавьте URL-адрес в urlpatterns: path('', views.home, name='home')
Представления на основе классов
    1. Добавьте импорт: from other_app.views import Home
    2. Добавьте URL-адрес в шаблоны URL-адресов: path('', Home.as_view(), name='home')
Включение другой конфигурации URL
    1. Импортируйте функцию include(): из django.urls import include, path
    2. Добавьте URL-адрес в urlpatterns: path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


from products.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('delivery/', include('delivery.urls', namespace='delivery')),
    path('disk/', include('disk.urls', namespace='disk')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('tires/', include('tires.urls', namespace='tires')),
    path('tredin/', include('tredin.urls', namespace='tredin')),


]


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User


class Blog(models.Model):  # Блог
    title = models.CharField('Заголовок записи', max_length=100)
    description = models.TextField('Текст в записи')
    author = models.ForeignKey(to=User, on_delete=models.CASCADE, max_length=100)
    date = models.DateTimeField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image_blog/')

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return f'{self.title}, {self.author}'


class Comments(models.Model):
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=5000)
    blog = models.ForeignKey(Blog, verbose_name='Публикация', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.blog}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic.base import View
from django.views.generic.list import ListView
from blog.models import Blog
from common.views import DescriptionMixin, TitleMixin
from .form import CommentsForm


class BlogView(TitleMixin, DescriptionMixin, View):
    """"Вывод записи"""
    title = 'Блог'
    description = 'Продажа шин и дисков в Екатеринбурге по выгодным ценам в интернет магазине автошин Продажа Шин 96. ' \
                  'Подробная информация о покупке шин и дисков по телефону: +7-961-777-5818'

    def get(self, request):
        blogs = Blog.objects.all()     # Указываем что передаем шаблону
        return render(request, 'blog/blog.html', {'blog_list': blogs})


class BlogDetail(TitleMixin, DescriptionMixin, View):
    """"Отдельная страница записи"""
    title = 'Блог'
    description = 'Продажа шин и дисков в Екатеринбурге по выгодным ценам в интернет магазине автошин Продажа Шин 96. ' \
                  'Подробная информация о покупке шин и дисков по телефону: +7-961-777-5818'

    def get(self, request, pk):
        blog = Blog.objects.get(id=pk)
        return render(request, 'blog/blog_detail.html', {'blog': blog})


class AddComments(LoginRequiredMixin, View):
    """Добавление комментария после регистрации"""
    @method_decorator(login_required)
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.blog_id = pk
            form.save()
        return redirect(f'/blog/{pk}')

templates/blog/blog.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static '/vendor/css/index.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'vendor/css/style.css' %}" type="text/css" media="all" />
{% endblock %}

{% block content %}
	{% for blog in blog_list %}
<body>
	<div class="shell">
		<div class="border">
			<div id="main">
				<div id="content" class="left">
					<div class="item">
						<div class="image left">
							<a href="#"><img src="{{ blog.img.url }}" width="200" alt="" /></a>
						</div>
							<div class="text left">
								<h4>
									<a href="{{ blog.id }}">{{ blog.title }}</a>
								</h4>
								<p>{{ blog.description }}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
				</div>
			</div>
				<div class="cl">&nbsp;</div>
		</div>
	</div>
</body>
	{% endfor %}
{% endblock %}

{% block footer %}
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">ПродажаШин96.рф &copy; Store 2022</p>
		</div>
	</footer>
{% endblock %}

templates/blog/blog_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static '/vendor/css/index.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'vendor/css/style.css' %}" type="text/css" media="all" />
{% endblock %}

{% block content %}

<body>
	<div class="shell">
		<div class="border">
			<div id="main">
				<div id="content" class="left">
					<div class="projects">
						<h3>{{ blog.title }}</h3>
					<p align="center">
						<img src="{{ blog.img.url }}" width="50%" alt="" /></a>
					</p>
						<div class="item">
								<div class="text left">
									<p>{{ blog.description }}</p>
							</div>
							<div class="cl">&nbsp;</div>
					</div>
					</div>
				</div>
			</div>
				<div class="cl">&nbsp;</div>
			<div>
				<div>
					<h6>Комментарии</h6>
				</div>
				{% for comment in blog.comments_set.all %}
				<div class="view-comment">
					<h8>Имя:</h8> <h6>{{ comment.name }}</h6>
					<p>
						<h8>Комментарии:</h8> <h6>{{ comment.text_comments }}</h6>
					</p>
				</div>
				{% endfor %}
			</div>
			<div class="form-comment">
				<h6>Оставить Комментарии</h6>
				<div>
					<form action="{% url 'blog:add_comments' blog.id %}" method="post">
					{% csrf_token %}
						<div>
							<label>Ваш комментарий</label>
							<textarea name="text_comments"></textarea>
						</div>
						<div>
							<label>Ваше Имя *</label>
							<input type="text" name="name">
						</div>
						<div>
							<label>Ваше Email *</label>
							<input type="email" name="email">
						</div>
						<div>
							<input type="submit">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

</body>

{% endblock %}

{% block footer %}
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">ПродажаШин96.рф &copy; Store 2022</p>
		</div>
	</footer>
{% endblock %}